export type Point = { x: number; y: number };
export type Size = { width: number; height: number };

export type Block = {
  id: string;
  content: string;
  alternatives: Block[];
  position?: Point;
  size?: Size;
};

export type BlocksDocument = {
  version: 1;
  blocks: Block[];
};

const TYPST_HEADER = [
  "// Generated by Blocks. Edit the .blocks document, not this export.",
  "#set page(margin: 1in)",
  '#set text(font: "Libertinus Serif", size: 11pt)',
].join("\n");

export const PRIMARY_WIDTH = 320;
export const ALTERNATIVE_WIDTH = 250;
export const PRIMARY_HEIGHT = 160;
export const ALTERNATIVE_HEIGHT = 140;
const SPINE_X = 820;
const SPINE_TOP = 100;
const SPINE_GAP = 220;
const ALTERNATIVE_X_GAP = 110;
const ALTERNATIVE_Y_GAP = 155;

export const starterDocument: BlocksDocument = {
  version: 1,
  blocks: [
    {
      id: "opening",
      content:
        "Begin writing here. Each card on the centre line is part of the current document.",
      alternatives: [
        {
          id: "opening-alt",
          content:
            "An alternate opening can sit beside the main paragraph without losing it.",
          alternatives: [],
        },
        {
          id: "opening-alt-two",
          content:
            "A second alternate can sit on the other side of the primary spine.",
          alternatives: [],
        },
      ],
    },
    {
      id: "second",
      content:
        "Move a paragraph up or down to change the spine. Create alternates whenever you want to try a different direction.",
      alternatives: [],
    },
  ],
};

function makeId() {
  return (
    crypto.randomUUID?.() ??
    `block-${Date.now()}-${Math.random().toString(16).slice(2)}`
  );
}

export function createBlock(content = ""): Block {
  return { id: makeId(), content, alternatives: [] };
}

export function defaultPrimaryPosition(index: number): Point {
  return { x: SPINE_X, y: SPINE_TOP + index * SPINE_GAP };
}

export function defaultAlternativePosition(
  primary: Point,
  index: number,
): Point {
  const side = index === 0 ? -1 : 1;
  return {
    x:
      side < 0
        ? primary.x - ALTERNATIVE_WIDTH - ALTERNATIVE_X_GAP
        : primary.x + PRIMARY_WIDTH + ALTERNATIVE_X_GAP,
    y: primary.y + (side < 0 ? 0 : index - 1) * ALTERNATIVE_Y_GAP + 13,
  };
}

export function primaryPosition(block: Block, index: number): Point {
  return block.position ?? defaultPrimaryPosition(index);
}

export function alternativePosition(
  primary: Block,
  primaryIndex: number,
  alternative: Block,
  alternativeIndex: number,
): Point {
  return (
    alternative.position ??
    defaultAlternativePosition(
      primaryPosition(primary, primaryIndex),
      alternativeIndex,
    )
  );
}

export function primarySize(block: Block): Size {
  return block.size ?? { width: PRIMARY_WIDTH, height: PRIMARY_HEIGHT };
}

export function alternativeSize(block: Block): Size {
  return block.size ?? { width: ALTERNATIVE_WIDTH, height: ALTERNATIVE_HEIGHT };
}

export function parseDocument(contents: string): BlocksDocument | null {
  try {
    const candidate = JSON.parse(contents) as Partial<BlocksDocument>;
    if (candidate.version === 1 && Array.isArray(candidate.blocks))
      return { version: 1, blocks: candidate.blocks };
  } catch {
    return null;
  }

  const blocks = contents
    .split(/\n\s*\n/)
    .map((content) => content.trim())
    .filter(Boolean)
    .map((content) => createBlock(content));
  return { version: 1, blocks: blocks.length ? blocks : [createBlock()] };
}

export function serializeDocument(document: BlocksDocument) {
  return `${JSON.stringify(document, null, 2)}\n`;
}

export function documentToTypst(document: BlocksDocument) {
  const body = document.blocks
    .map((block) => block.content.trim())
    .join("\n\n");
  return `${TYPST_HEADER}\n\n${body}`.trimEnd() + "\n";
}

export type TypstBlockRange = {
  blockId: string;
  startLine: number;
  endLine: number;
  localStartLine: number;
  localStartCharacter: number;
};

export function typstBlockRanges(document: BlocksDocument): TypstBlockRange[] {
  let line = TYPST_HEADER.split("\n").length + 1;
  return document.blocks.map((block) => {
    const trimmed = block.content.trim();
    const lineCount = trimmed.split("\n").length;
    const leadingLength = trimmed ? block.content.indexOf(trimmed) : 0;
    const leading = block.content.slice(0, leadingLength);
    const localStartLine = leading.split("\n").length - 1;
    const lastLeadingNewline = leading.lastIndexOf("\n");
    const range = {
      blockId: block.id,
      startLine: line,
      endLine: line + lineCount - 1,
      localStartLine,
      localStartCharacter: leading.length - lastLeadingNewline - 1,
    };
    // Sections are separated by two newlines. A section with N visual lines
    // already contains N - 1 newlines, so the next section starts N + 1 lines on.
    line += lineCount + 1;
    return range;
  });
}

export function replacePrimary(
  document: BlocksDocument,
  primaryId: string,
  next: Block,
): BlocksDocument {
  return {
    ...document,
    blocks: document.blocks.map((block) =>
      block.id === primaryId ? next : block,
    ),
  };
}

export function getPrimary(document: BlocksDocument, primaryId: string) {
  return document.blocks.find((block) => block.id === primaryId);
}

export function updateAlternative(
  block: Block,
  alternativeId: string,
  change: (alternative: Block) => Block,
): Block {
  return {
    ...block,
    alternatives: block.alternatives.map((alternative) => {
      if (alternative.id === alternativeId) return change(alternative);
      return {
        ...alternative,
        alternatives: alternative.alternatives.map((nested) =>
          nested.id === alternativeId ? change(nested) : nested,
        ),
      };
    }),
  };
}

export function translatePrimaryGroup(
  block: Block,
  primaryIndex: number,
  nextPosition: Point,
): Block {
  const currentPosition = primaryPosition(block, primaryIndex);
  const dx = nextPosition.x - currentPosition.x;
  const dy = nextPosition.y - currentPosition.y;
  return {
    ...block,
    position: nextPosition,
    alternatives: block.alternatives.map((alternative, alternativeIndex) => {
      const position = alternativePosition(
        block,
        primaryIndex,
        alternative,
        alternativeIndex,
      );
      return {
        ...alternative,
        position: { x: position.x + dx, y: position.y + dy },
      };
    }),
  };
}
